### ISSUE TITLE
error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/ovs_exporter#2]
```sh
ts=2024-08-01T14:29:05.600Z caller=ovs_exporter.go:50 level=info msg="Starting ovs_exporter" version="(version=, branch=, revision=444d9d9706127e76525edcc202d65ac4d14ba4f2)"
ts=2024-08-01T14:29:05.600Z caller=ovs_exporter.go:51 level=info msg="Build context" build_context="(go=go1.22.2, platform=linux/amd64, user=, date=, tags=unknown)"
ts=2024-08-01T14:29:05.613Z caller=tls_config.go:313 level=info msg="Listening on" address=[::]:9272
ts=2024-08-01T14:29:05.613Z caller=tls_config.go:316 level=info msg="TLS is disabled." http2=false address=[::]:9272
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x922f88]

goroutine 28 [running]:
github.com/vexxhost/ovs_exporter/collector.(*InterfaceCollector).collectAdminState(_, _, {{0xc0001207b0, 0x24}, 0xc000293280, 0x0, 0x0, 0x0, {0x0, 0x0, ...}, ...})
  /src/collector/interface.go:120 +0x88
github.com/vexxhost/ovs_exporter/collector.(*InterfaceCollector).Collect(0xc00031b1a0, 0xc00049c060)
  /src/collector/interface.go:99 +0x254
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
  /go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/registry.go:455 +0x105
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather in goroutine 24
  /go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/registry.go:547 +0xbab
```

**Comment by okozachenko1203** [comment]
@mnaser could you check this?
